{"uid":"8cf04dca0d2411e2","name":"test_promt_alert_result","fullName":"tests.test_alert_frame_window.TestAlertPage#test_promt_alert_result","historyId":"33d98916333a44f9d3c92bb68a1880f4","time":{"start":1695163099962,"stop":1695163099962,"duration":0},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5621a844de23 <unknown>\n#1 0x5621a81767a7 <unknown>\n#2 0x5621a81a150a <unknown>\n#3 0x5621a819ea25 <unknown>\n#4 0x5621a81ded92 <unknown>\n#5 0x5621a81de3af <unknown>\n#6 0x5621a81d5de3 <unknown>\n#7 0x5621a81a9a7b <unknown>\n#8 0x5621a81aa81e <unknown>\n#9 0x5621a840f638 <unknown>\n#10 0x5621a8413507 <unknown>\n#11 0x5621a841dc4c <unknown>\n#12 0x5621a8414136 <unknown>\n#13 0x5621a83e29cf <unknown>\n#14 0x5621a8437b98 <unknown>\n#15 0x5621a8437d68 <unknown>\n#16 0x5621a8446cb3 <unknown>\n#17 0x7f9196094b43 <unknown>","statusTrace":"@pytest.fixture(scope='function')\n    def driver():\n        start_time = str(datetime.now().strftime(\"%d-%m-%Y %H:%M:%S\"))\n        full_test_name = os.environ.get(\"PYTEST_CURRENT_TEST\").split('::')\n        test_name = full_test_name[-1]\n        test_name = test_name.replace(' (setup)', '')\n        print(f'\\nStart Test: <{test_name}> {start_time}')\n        options = Options()\n        options.add_experimental_option('excludeSwitches', ['enable-logging'])\n        service = Service(ChromeDriverManager().install())\n>       driver = webdriver.Chrome(service=service)\n\nconftest.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:290: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f95dfbd9db0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: Chrome failed to start: exited a...\\\\n#15 0x5621a8437d68 \\\\u003Cunknown>\\\\n#16 0x5621a8446cb3 \\\\u003Cunknown>\\\\n#17 0x7f9196094b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\nE         (unknown error: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5621a844de23 <unknown>\nE       #1 0x5621a81767a7 <unknown>\nE       #2 0x5621a81a150a <unknown>\nE       #3 0x5621a819ea25 <unknown>\nE       #4 0x5621a81ded92 <unknown>\nE       #5 0x5621a81de3af <unknown>\nE       #6 0x5621a81d5de3 <unknown>\nE       #7 0x5621a81a9a7b <unknown>\nE       #8 0x5621a81aa81e <unknown>\nE       #9 0x5621a840f638 <unknown>\nE       #10 0x5621a8413507 <unknown>\nE       #11 0x5621a841dc4c <unknown>\nE       #12 0x5621a8414136 <unknown>\nE       #13 0x5621a83e29cf <unknown>\nE       #14 0x5621a8437b98 <unknown>\nE       #15 0x5621a8437d68 <unknown>\nE       #16 0x5621a8446cb3 <unknown>\nE       #17 0x7f9196094b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1695163093572,"stop":1695163093589,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"driver","time":{"start":1695163099962,"stop":1695163101010,"duration":1048},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5621a844de23 <unknown>\n#1 0x5621a81767a7 <unknown>\n#2 0x5621a81a150a <unknown>\n#3 0x5621a819ea25 <unknown>\n#4 0x5621a81ded92 <unknown>\n#5 0x5621a81de3af <unknown>\n#6 0x5621a81d5de3 <unknown>\n#7 0x5621a81a9a7b <unknown>\n#8 0x5621a81aa81e <unknown>\n#9 0x5621a840f638 <unknown>\n#10 0x5621a8413507 <unknown>\n#11 0x5621a841dc4c <unknown>\n#12 0x5621a8414136 <unknown>\n#13 0x5621a83e29cf <unknown>\n#14 0x5621a8437b98 <unknown>\n#15 0x5621a8437d68 <unknown>\n#16 0x5621a8446cb3 <unknown>\n#17 0x7f9196094b43 <unknown>\n\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/home/runner/work/DemoQA/DemoQA/conftest.py\", line 23, in driver\n    driver = webdriver.Chrome(service=service)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 56, in __init__\n    super().__init__(\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 206, in __init__\n    self.start_session(capabilities)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 290, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 345, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true}],"testStage":{"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5621a844de23 <unknown>\n#1 0x5621a81767a7 <unknown>\n#2 0x5621a81a150a <unknown>\n#3 0x5621a819ea25 <unknown>\n#4 0x5621a81ded92 <unknown>\n#5 0x5621a81de3af <unknown>\n#6 0x5621a81d5de3 <unknown>\n#7 0x5621a81a9a7b <unknown>\n#8 0x5621a81aa81e <unknown>\n#9 0x5621a840f638 <unknown>\n#10 0x5621a8413507 <unknown>\n#11 0x5621a841dc4c <unknown>\n#12 0x5621a8414136 <unknown>\n#13 0x5621a83e29cf <unknown>\n#14 0x5621a8437b98 <unknown>\n#15 0x5621a8437d68 <unknown>\n#16 0x5621a8446cb3 <unknown>\n#17 0x7f9196094b43 <unknown>","statusTrace":"@pytest.fixture(scope='function')\n    def driver():\n        start_time = str(datetime.now().strftime(\"%d-%m-%Y %H:%M:%S\"))\n        full_test_name = os.environ.get(\"PYTEST_CURRENT_TEST\").split('::')\n        test_name = full_test_name[-1]\n        test_name = test_name.replace(' (setup)', '')\n        print(f'\\nStart Test: <{test_name}> {start_time}')\n        options = Options()\n        options.add_experimental_option('excludeSwitches', ['enable-logging'])\n        service = Service(ChromeDriverManager().install())\n>       driver = webdriver.Chrome(service=service)\n\nconftest.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py:45: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py:56: in __init__\n    super().__init__(\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:206: in __init__\n    self.start_session(capabilities)\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:290: in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py:345: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f95dfbd9db0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: Chrome failed to start: exited a...\\\\n#15 0x5621a8437d68 \\\\u003Cunknown>\\\\n#16 0x5621a8446cb3 \\\\u003Cunknown>\\\\n#17 0x7f9196094b43 \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: Dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                import json\n    \n                try:\n                    value = json.loads(value_json)\n                    if len(value) == 1:\n                        value = value[\"value\"]\n                    status = value.get(\"error\", None)\n                    if not status:\n                        status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                        message = value.get(\"value\") or value.get(\"message\")\n                        if not isinstance(message, str):\n                            value = message\n                            message = message.get(\"message\")\n                    else:\n                        message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: Type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\nE         (unknown error: DevToolsActivePort file doesn't exist)\nE         (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nE       Stacktrace:\nE       #0 0x5621a844de23 <unknown>\nE       #1 0x5621a81767a7 <unknown>\nE       #2 0x5621a81a150a <unknown>\nE       #3 0x5621a819ea25 <unknown>\nE       #4 0x5621a81ded92 <unknown>\nE       #5 0x5621a81de3af <unknown>\nE       #6 0x5621a81d5de3 <unknown>\nE       #7 0x5621a81a9a7b <unknown>\nE       #8 0x5621a81aa81e <unknown>\nE       #9 0x5621a840f638 <unknown>\nE       #10 0x5621a8413507 <unknown>\nE       #11 0x5621a841dc4c <unknown>\nE       #12 0x5621a8414136 <unknown>\nE       #13 0x5621a83e29cf <unknown>\nE       #14 0x5621a8437b98 <unknown>\nE       #15 0x5621a8437d68 <unknown>\nE       #16 0x5621a8446cb3 <unknown>\nE       #17 0x7f9196094b43 <unknown>\n\n/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py:229: WebDriverException","steps":[],"attachments":[{"uid":"3727c4d0a484b446","name":"stdout","source":"3727c4d0a484b446.txt","type":"text/plain","size":59}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[],"labels":[{"name":"feature","value":"Test Alert Page"},{"name":"suite","value":"Test Alert Frame Windows"},{"name":"parentSuite","value":"tests"},{"name":"subSuite","value":"TestAlertFrameWindows"},{"name":"host","value":"fv-az572-268"},{"name":"thread","value":"2018-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_alert_frame_window"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"8cf04dca0d2411e2.json","parameterValues":[]}